# Generated by Django 3.0.7 on 2020-06-22 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BkId', models.IntegerField(primary_key=True, serialize=False, verbose_name='Bkid')),
                ('BkTitle', models.CharField(max_length=15, verbose_name='BkTitle')),
                ('BkAuthor', models.CharField(max_length=15, verbose_name='BkAuthor')),
                ('BkPublisher', models.CharField(max_length=15, verbose_name='BkPublisher')),
                ('BkPubDate', models.CharField(max_length=8, verbose_name='BkPubDate')),
                ('Category', models.CharField(max_length=15, verbose_name='Category')),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Rating')),
                ('ReviewNum', models.IntegerField(null=True, verbose_name='ReviewField')),
            ],
            options={
                'db_table': 'Book',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False, verbose_name='UserId')),
                ('UserName', models.CharField(max_length=15, verbose_name='UserName')),
                ('Password', models.CharField(max_length=15, verbose_name='Password')),
                ('CreateTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('ReviewId', models.IntegerField(primary_key=True, serialize=False, verbose_name='ReviewId')),
                ('ReviewCont', models.TextField(verbose_name='ReviewCont')),
                ('ReviewDate', models.DateField(auto_now_add=True)),
                ('Rating', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Rating')),
                ('BkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Book')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
            options={
                'db_table': 'Review',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('CoId', models.IntegerField(primary_key=True, serialize=False, verbose_name='CoId')),
                ('CoName', models.CharField(max_length=15, verbose_name='CoName')),
                ('CoCreateDate', models.DateTimeField(auto_now_add=True)),
                ('CoUpdateDate', models.DateTimeField(auto_now=True)),
                ('CoOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.User')),
            ],
            options={
                'db_table': 'Collection',
            },
        ),
        migrations.CreateModel(
            name='CoBk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BkId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Book')),
                ('CoId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Collection')),
            ],
            options={
                'db_table': 'CoBk',
            },
        ),
    ]
