# Generated by Django 3.0.7 on 2020-06-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='UserName',
            field=models.CharField(max_length=15, unique=True, verbose_name='UserName'),
        ),
    ]
