# Generated by Django 3.0.7 on 2020-06-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200620_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('BkId', models.IntegerField(primary_key=True, serialize=False, verbose_name='Bkid')),
                ('BkTitle', models.CharField(max_length=15, verbose_name='BkTitle')),
                ('BkAuthor', models.CharField(max_length=15, verbose_name='BkAuthor')),
                ('BkPublisher', models.CharField(max_length=15, verbose_name='BkPublisher')),
                ('BkPubDate', models.CharField(max_length=8, verbose_name='BkPubDate')),
                ('Category', models.CharField(max_length=15, verbose_name='Category')),
                ('Rating', models.CharField(max_length=15, null=True, verbose_name='Rating')),
                ('ReviewNum', models.IntegerField(null=True, verbose_name='ReviewField')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.IntegerField(primary_key=True, serialize=False, verbose_name='UserId')),
                ('Password', models.CharField(max_length=15, verbose_name='Password')),
                ('CreateTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentunion',
            name='unionRoot',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='studentUnion',
        ),
    ]
