# Generated by Django 3.0.7 on 2020-06-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200623_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BkId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Bkid'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='CoId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='CoId'),
        ),
        migrations.AlterField(
            model_name='review',
            name='ReviewId',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ReviewId'),
        ),
    ]
