# Generated by Django 3.0.7 on 2020-06-21 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200621_1551'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='Book',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
